baseURL = 'https://example.org/'
title = 'mutoxu=N'
theme = 'gokarna'
languageCode = 'ja'
DefaultContentLanguage = 'ja'

[pagination]
pagerSize = 5


[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'gruvbox'
tabWidth = 4
