baseURL = 'https://example.org/'
languageCode = 'ja'
title = 'mutoxu=N'
theme = 'ananke'


[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'gruvbox'
tabWidth = 4
